apiVersion: v1
kind: Service
metadata:
  name: gateway-public
spec:
  selector:
    app: gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30036
  type: NodePort
