apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
spec:
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
