apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../minikube

patchesStrategicMerge:
- elastic/es-data-stateful.yaml
- elastic/es-master.yaml
- postgres/postgres-deployment.yaml
